name: Lighthouse CI Audit

on:
  workflow_dispatch:
  push:

jobs:
  lighthouse_audit:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        formFactor: [desktop, tablet]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Find Project Directory
        id: find_dir
        run: |
          PROJECT_DIR=$(find . -name "package.json" -exec dirname {} \; | head -n 1)
          echo "PROJECT_DIR=$PROJECT_DIR" >> $GITHUB_ENV

      - name: Install dependencies and LHCI
        run: |
          cd ${{ env.PROJECT_DIR }}
          npm install
          npm install -g @lhci/cli serve wait-on

      - name: Build Astro project
        run: |
          cd ${{ env.PROJECT_DIR }}
          npm run build

      - name: Generate URLs
        run: |
          cd ${{ env.PROJECT_DIR }}
          mkdir -p .lighthouseci
          find dist -name '*.html' \
            | sed -e 's|dist||' -e 's|/index.html||' \
            | awk '{print "http://localhost:4321"$0}' > .lighthouseci/urls.txt
          cat .lighthouseci/urls.txt

      - name: Create Lighthouse CI Config for ${{ matrix.formFactor }}
        run: |
          cd ${{ env.PROJECT_DIR }}

          if [ "${{ matrix.formFactor }}" = "desktop" ]; then
            WIDTH=1350
            HEIGHT=940
            DSF=1
            MOBILE=false
          else
            WIDTH=768
            HEIGHT=1024
            DSF=2
            MOBILE=true
          fi

          cat << EOF > lighthouserc.json
          {
            "ci": {
              "collect": {
                "staticDistDir": "./dist",
                "settings": {
                  "formFactor": "${{ matrix.formFactor }}",
                  "screenEmulation": {
                    "width": $WIDTH,
                    "height": $HEIGHT,
                    "deviceScaleFactor": $DSF,
                    "mobile": $MOBILE,
                    "disabled": false
                  }
                }
              },
              "upload": {
                "target": "filesystem",
                "outputDir": "./lhci-report-${{ matrix.formFactor }}"
              },
              "assert": {
                "assertions": {
                  "categories:performance": ["warn", { "minScore": 0.5 }],
                  "categories:accessibility": ["warn", { "minScore": 0.3 }]
                }
              }
            }
          }
          EOF

      - name: Serve static dist and run LHCI collect for ${{ matrix.formFactor }}
        run: |
          cd ${{ env.PROJECT_DIR }}
          serve dist -l 4321 &
          wait-on http://localhost:4321
          lhci collect --config=lighthouserc.json $(sed -e 's|^|--url=|' .lighthouseci/urls.txt)

      - name: Upload Lighthouse report (${{ matrix.formFactor }})
        uses: actions/upload-artifact@v4
        with:
          name: lighthouse-report-${{ matrix.formFactor }}
          path: ${{ env.PROJECT_DIR }}/lhci-report-${{ matrix.formFactor }}
