name: CI

on:
  push:
  workflow_dispatch:

jobs:
  lighthouse_audit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install Dependencies
        run: npm ci

      - name: Build Astro Project
        run: npm run build

      - name: Install Static Server
        run: npm install -g serve

      - name: Serve & Run Lighthouse Audit
        run: |
          serve dist -l 4321 &  # Start server on port 8080
          sleep 5               # Wait for server to start
          lhci collect

      - name: Upload Lighthouse Report
        uses: actions/upload-artifact@v4
        with:
          name: lighthouse-report
          path: .lighthouseci/
