name: CI

on:
  push:
  workflow_dispatch:

jobs:
  lighthouse_audit:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        formfactor: [[mobile,320,480], [desktop,1920,1080], [tablet,1024,768], [laptop,1366,768]]

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install Dependencies
        run: npm ci

      - name: Build Astro Project
        run: npm run build

      - name: Check dist folder HTML files
        run: |
          echo "Listing HTML files in dist:"
          find dist -name '*.html'

      - name: Generate LHCI URLs
        run: |
          mkdir -p .lighthouseci
          find dist -name '*.html' \
            | sed -e 's|dist||' -e 's|/index.html||' \
            | awk '{print "http://localhost:4321"$0}' > .lighthouseci/urls.txt
          echo "URLs generated in .lighthouseci/urls.txt:"
          cat .lighthouseci/urls.txt

      - name: Check URLs not empty
        run: |
          if [ ! -s .lighthouseci/urls.txt ]; then
            echo "ERROR: urls.txt is empty! No URLs to audit."
            exit 1
          fi

      - name: Create Lighthouse CI Config
        run: |
          cd ${{ env.PROJECT_DIR }}
          cat << EOF > .lighthouserc.${{ matrix.formfactor[0] }}.json
          {
            "ci": {
              "collect": {
                "numberOfRuns": 1,
                "url": [],
                "settings": {
                  "preset": ${{ matrix.formfactor[0] }},
                  "emulatedFormFactor": "${{ matrix.formfactor[0] }}",
                  "screenEmulation": {
                    "mobile": false,
                    "width": ${{matrix.formfactor[1]}},
                    "height": ${{matrix.formfactor[2]}},
                    "deviceScaleFactor": 2,
                    "disabled": false
                  },
                  "throttling": {
                    "rttMs": 40,
                    "throughputKbps": 10240,
                    "cpuSlowdownMultiplier": 1,
                    "requestLatencyMs": 0,
                    "downloadThroughputKbps": 0,
                    "uploadThroughputKbps": 0
                  }
                }
              },
              "upload": {
                "target": "filesystem",
                "outputDir": "./lhci-report-${{ matrix.formfactor[0] }}",
              }
            }
          }
          EOF

      - name: Update desktop Config with URLs
        run: |
          urls=$(jq -R -s -c 'split("\n")[:-1]' < .lighthouseci/urls.txt)
          jq --argjson urls "$urls" '.ci.collect.url = $urls' .lighthouserc.${{matrix.formfactor[0]}}.json > tmp && mv tmp .lighthouserc.${{matrix.formfactor[0]}}.json

      - name: Install Static Server and LHCI CLI
        run: npm install -g serve @lhci/cli wait-on

      - name: Run Lighthouse Audit - (${{ matrix.formfactor[0] }})
        run: |
          serve dist -l 4321 &
          wait-on http://localhost:4321
          lhci autorun --config=.lighthouserc.${{matrix.formfactor[0]}}.json
        env:
          PORT: 4321

      - name: Kill Serve (${{ matrix.formfactor[0] }})
        run: kill $(lsof -t -i:4321) || true


      - name: Upload Lighthouse Tablet Report
        uses: actions/upload-artifact@v4
        with:
          name: lighthouse-report-${{ matrix.formfactor[0] }}
          path: lhci-report-${{ matrix.formfactor[0] }}
