name: CI

on:
  push:
  workflow_dispatch:

jobs:
  lighthouse_audit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install Dependencies
        run: npm ci

      - name: Build Astro Project
        run: npm run build

      - name: Check dist folder HTML files
        run: |
          echo "Listing HTML files in dist:"
          find dist -name '*.html'

      - name: Generate LHCI URLs
        run: |
          mkdir -p .lighthouseci
          find dist -name '*.html' \
            | sed -e 's|dist||' -e 's|/index.html||' \
            | awk '{print "http://localhost:4321"$0}' > .lighthouseci/urls.txt
          echo "URLs generated in .lighthouseci/urls.txt:"
          cat .lighthouseci/urls.txt

      - name: Check URLs not empty
        run: |
          if [ ! -s .lighthouseci/urls.txt ]; then
            echo "ERROR: urls.txt is empty! No URLs to audit."
            exit 1
          fi

      - name: Update lighthouserc-tablet.json with URLs
        run: |
          urls=$(jq -R -s -c 'split("\n")[:-1]' < .lighthouseci/urls.txt)
          jq --argjson urls "$urls" '.ci.collect.url = $urls' lighthouserc-tablet.json > tmp && mv tmp lighthouserc-tablet.json

          
      - name: Update lighthouserc-laptop.json with URLs
        run: |
          urls=$(jq -R -s -c 'split("\n")[:-1]' < .lighthouseci/urls.txt)
          jq --argjson urls "$urls" '.ci.collect.url = $urls' lighthouserc-laptop.json > tmp && mv tmp lighthouserc-laptop.json

      - name: Install Static Server and LHCI CLI
        run: npm install -g serve @lhci/cli wait-on

      - name: Serve & Run Lighthouse Audit for Tablet
        run: |
          set -x
          serve dist -l 4321 &
          wait-on http://localhost:4321
          cd ${{ github.workspace }}
          echo "Running LHCI autorun (collectMatrix)..."
          lhci autorun --config=lighthouserc-tablet.json 

      - name: Serve & Run Lighthouse Audit for Laptop
        run: |
          set -x
          serve dist -l 4321 &
          wait-on http://localhost:4321
          cd ${{ github.workspace }}
          echo "Running LHCI autorun (collectMatrix)..."
          lhci autorun --config=lighthouserc-laptop.json 

      - name: Upload Lighthouse Tablet Report
        uses: actions/upload-artifact@v4
        with:
          name: lighthouse-report-tablet
          path: lhci-report-tablet

      - name: Upload Lighthouse Laptop Report
        uses: actions/upload-artifact@v4
        with:
          name: lighthouse-report-laptop
          path: lhci-report-laptop


