name: CI

on:
  push:
  workflow_dispatch:

jobs:
  lighthouse_audit:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        name: [mobile, desktop, tablet, laptop]
        width: [default, 1920, 1024, 1366]
        height: [default, 1080, 768, 768]
        preset: [default, desktop, experimental, desktop]
        mobile: [true, false, true, false]
        disabled: [true, false, true, false]


    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install Dependencies
        run: npm ci

      - name: Build Astro Project
        run: npm run build

      - name: List HTML Files in dist
        run: |
          find dist -name '*.html'

      - name: Generate LHCI URLs
        run: |
          mkdir -p .lighthouseci
          find dist -name '*.html' \
            | sed -e 's|dist||' -e 's|/index.html||' \
            | awk '{print "http://localhost:4321"$0}' > .lighthouseci/urls.txt
          echo "Generated URLs:"
          cat .lighthouseci/urls.txt

      - name: Validate URLs file
        run: |
          if [ ! -s .lighthouseci/urls.txt ]; then
            echo "ERROR: urls.txt is empty! No URLs to audit."
            exit 1
          fi

      - name: Create Lighthouse Config
        run: |
          cat << EOF > .lighthouserc.${{ matrix.name }}.json
          {
            "ci": {
              "collect": {
                "numberOfRuns": 1,
                "url": [],
                "settings": {
                  "preset": "${{ matrix.preset }}",
                  "emulatedFormFactor": "${{ matrix.name }}",
                  "screenEmulation": {
                    "mobile": ${{ matrix.mobile }},
                    "width": ${{ matrix.width }},
                    "height": ${{ matrix.height }},
                    "deviceScaleFactor": 2,
                    "disabled": ${{ matrix.disabled }}
                  },
                  "throttling": {
                    "rttMs": 40,
                    "throughputKbps": 10240,
                    "cpuSlowdownMultiplier": 1
                  }
                }
              },
              "upload": {
                "target": "filesystem",
                "outputDir": "./lhci-report-${{ matrix.name }}"
              }
            }
          }
          EOF

      - name: Inject URLs into Config
        run: |
          urls=$(jq -R -s -c 'split("\n")[:-1]' < .lighthouseci/urls.txt)
          jq --argjson urls "$urls" '.ci.collect.url = $urls' \
            .lighthouserc.${{ matrix.name }}.json > tmp && mv tmp .lighthouserc.${{ matrix.name }}.json

      - name: Install Static Server and LHCI CLI
        run: npm install -g serve @lhci/cli wait-on

      - name: Run Lighthouse Audit
        run: |
          serve dist -l 4321 &
          wait-on http://localhost:4321
          lhci autorun --config=.lighthouserc.${{ matrix.name }}.json
        env:
          PORT: 4321

      - name: Kill Static Server
        run: kill $(lsof -t -i:4321) || true

      - name: Upload Report
        uses: actions/upload-artifact@v4
        with:
          name: lighthouse-report-${{ matrix.name }}
          path: lhci-report-${{ matrix.name }}
