name: CI

on:
  push:
  workflow_dispatch:

jobs:
  lighthouse_audit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install Dependencies
        run: npm ci

      - name: Build Astro Project
        run: npm run build

      - name: Generate LHCI URLs file
        run: |
          mkdir -p .lighthouseci
          # Extract paths and convert to clean URLs
          find dist -name '*.html' | sed -E 's|dist(/index)?\.html$|/|; s|dist/(.*)\.html$|/\1/|' > .lighthouseci/urls.txt
          echo "Lighthouse URLs:"
          cat .lighthouseci/urls.txt


      - name: Install Static Server and LHCI CLI
        run: npm install -g serve @lhci/cli wait-on

      - name: Serve & Run Lighthouse Audit
        run: |
          serve dist -l 4321 &         # Start server in background
          wait-on http://localhost:4321
          lhci collect --url=$(sed -e 's|^|http://localhost:4321|' .lighthouseci/urls.txt | tr '\n' ',' | sed 's/,$//')

      - name: List LHCI Reports
        run: ls -la .lighthouseci

      - name: Upload Lighthouse Report
        uses: actions/upload-artifact@v4
        with:
          name: lighthouse-report
          path: .lighthouseci/
