name: CI

on:
  push:
  workflow_dispatch:

jobs:
  lighthouse_audit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install Dependencies
        run: npm ci

      - name: Build Astro Project
        run: npm run build

      - name: Generate LHCI URLs file
        run: |
          mkdir -p .lighthouseci
          # Find all HTML files in dist and convert to URLs
          find dist -name '*.html' | sed 's|dist||' > .lighthouseci/urls.txt
          # Add root URL "/" if not present
          if ! grep -q "^/$" .lighthouseci/urls.txt; then
            echo "/" >> .lighthouseci/urls.txt
          fi
          cat .lighthouseci/urls.txt

      - name: Install Static Server and LHCI CLI
        run: npm install -g serve @lhci/cli

      - name: Install wait-on
        run: npm install -g wait-on

      - name: Serve & Run Lighthouse Audit
        run: |
          serve dist -l 4321 &         # Start server on port 4321 in background
          wait-on http://localhost:4321                  # Wait for server to be ready
          lhci collect --url=$(sed -e 's|^|http://localhost:4321|' .lighthouseci/urls.txt | tr '\n' ',' | sed 's/,$//')

      - name: Upload Lighthouse Report
        uses: actions/upload-artifact@v4
        with:
          name: lighthouse-report
          path: .lighthouseci/
      
      - name: List LHCI reports
        run: ls -la .lighthouseci


